spring:
  application:
    name : "user-api"
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
jwt :
  secret : ${SECRET_KEY_SOURCE}


