spring:
  application:
    name: "user-api"
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    show-sql: true
  datasource:
    url: ENC(iqEhPeyoO4MB9DNP/FwlvtNKJ707GMDumhMhTDdV3Ft/D2P+rSLblsJM/zezfpofMJOXoDthEmAauiaCPULs6KtmW2C5GfG0OFXLej6yBWddko8ms2cC/A==)
    password: ENC(YxJQuhf34uOnbS8x9xFeh/8hC4BO3OdX)
    username: ENC(JiKWkC8d7XLu+oiWGKVaPg==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
jwt:
  secret: ${SECRET_KEY_SOURCE}


payment-service:
  url: http://localhost:8085/api/internal/beanpay/v1