spring:
  profiles:
    activation:
      on-profile: prod
  application:
    name : "payment-api"
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    url: ENC(Fq3XI5xdxDMyXAMlMy3dyVEbepH4574caJpgxV8AAyg1i7gxyqAdppsei5hOsKY8dSCi5pE6cq+pcPoLptdxrGt/RCDmaTTT3EONf1aLmyoOxXdGzHL9bmYoLUv4qzJw)
    username: ENC(+p5Ip/ROTDnL5u2jcp/F9w==)
    password: ENC(TGQE//4tXoVvi1wuygHhMNcRZ8tIQXsn)
    hikari:
      maximum-pool-size: 50 #최대 pool 크기
      minimum-idle: 10 #최소 pool 크기
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      redisson-prefix: "redis://"
server:
  port: 8081


toss:
  secretKey: ENC(86ig+oZXxY6PDB8CYxIdqZVTM1sQCwW793bAtqQUzDH/yNl2loimvtFfQZhGa7e6)
  server:
    url: https://api.tosspayments.com/v1/payments