spring:
  application:
    name: product-search-api
  datasource:
    url: ENC(dQ7QRTJdnmnGE3t8op9hx7c6ifIjmRu9Tnk8tMo9WOPpp2Dhdldriyo/KKc2Gd3lMkR1spD2S3xEcP3TDZdmykSOcVywwlrglwlMM+Q3qleTgP8i2HMLvw==)
    password: ENC(YxJQuhf34uOnbS8x9xFeh/8hC4BO3OdX)
    username: ENC(JiKWkC8d7XLu+oiWGKVaPg==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  # es 계정정보는 여러 테스트 후 세팅 안정되면 변경 예정
  elasticsearch:
    username: elastic
    password: changeme
    uris: http://localhost:9200
