spring :
  application :
    name : product-management-api
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    show-sql: true
  datasource:
    url: ENC(dQ7QRTJdnmnGE3t8op9hx7c6ifIjmRu9Tnk8tMo9WOPpp2Dhdldriyo/KKc2Gd3lMkR1spD2S3xEcP3TDZdmykSOcVywwlrglwlMM+Q3qleTgP8i2HMLvw==)
    password: ENC(YxJQuhf34uOnbS8x9xFeh/8hC4BO3OdX)
    username: ENC(JiKWkC8d7XLu+oiWGKVaPg==)
    driver-class-name: com.mysql.cj.jdbc.Driver