name: qodana

on:
  push:
    branches:
      - develop
      - 'chore/qodana'
  pull_request:
    branches:
      - "**"

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
          
      - name: Validate Gradle Wrapper
        run: ./gradlew --version
        working-directory: JVM/intellij-coverage-agent/gradle
  
      - name: Run Tests
        run: ./gradlew test
        working-directory: JVM/intellij-coverage-agent/gradle
        
      - name: Create coverage-data directory and copy contents
        run: |
          mkdir -p JVM/intellij-coverage-agent/gradle/.qodana/code-coverage
          cp -R JVM/intellij-coverage-agent/gradle/build/kover/bin-reports/* JVM/intellij-coverage-agent/gradle/.qodana/code-coverage/
        
      - name: Archive coverage data
        uses: actions/upload-artifact@v2
        with:
          name: gradle-coverage-data.zip
          path: JVM/intellij-coverage-agent/gradle/.qodana/code-coverage     
      
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
